assigness: []
harvest_options:
  goldcopy: false
  path: s3://ooi-data
  refresh: true
  test: false
instrument: CE07SHSM-MFD35-04-ADCPTC000
stream:
  method: telemetered
  name: adcp_engineering
workflow_config:
  schedule: 0 0 * * *
